// flow-typed signature: 26267caeb9d0789f8f09f4715db2b1c7
// flow-typed version: <<STUB>>/chirashi-event-emitter_v2.0.2/flow_v0.52.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'chirashi-event-emitter'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'chirashi-event-emitter' {
  /**
   * The TEventEmitter type.
   */
  declare type TEventEmitter = {
    on (event: string, callback: Function): () => void,
    off (event: string, callback: Function): void,
    emit (event: string, ...args: any): void
  }

  declare module.exports: () => TEventEmitter
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'chirashi-event-emitter/dist/chirashi-event-emitter.common' {
  declare module.exports: any;
}

declare module 'chirashi-event-emitter/dist/chirashi-event-emitter' {
  declare module.exports: any;
}

declare module 'chirashi-event-emitter/dist/chirashi-event-emitter.min' {
  declare module.exports: any;
}

declare module 'chirashi-event-emitter/lib/EventEmitter' {
  declare module.exports: any;
}

declare module 'chirashi-event-emitter/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'chirashi-event-emitter/dist/chirashi-event-emitter.common.js' {
  declare module.exports: $Exports<'chirashi-event-emitter/dist/chirashi-event-emitter.common'>;
}
declare module 'chirashi-event-emitter/dist/chirashi-event-emitter.js' {
  declare module.exports: $Exports<'chirashi-event-emitter/dist/chirashi-event-emitter'>;
}
declare module 'chirashi-event-emitter/dist/chirashi-event-emitter.min.js' {
  declare module.exports: $Exports<'chirashi-event-emitter/dist/chirashi-event-emitter.min'>;
}
declare module 'chirashi-event-emitter/lib/EventEmitter.js' {
  declare module.exports: $Exports<'chirashi-event-emitter/lib/EventEmitter'>;
}
declare module 'chirashi-event-emitter/lib/index.js' {
  declare module.exports: $Exports<'chirashi-event-emitter/lib/index'>;
}
